# Generated by Django 4.2.9 on 2024-08-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atap', models.CharField(default='default_atap', max_length=50)),
                ('rangka_atap', models.CharField(default='default_rangka_atap', max_length=50)),
                ('kolom_bangunan', models.CharField(default='default_kolom_bangunan', max_length=50)),
            ],
            options={
                'verbose_name': 'Kriteria',
                'verbose_name_plural': 'Kriteria',
            },
        ),
        migrations.AddField(
            model_name='shelter',
            name='atap',
            field=models.CharField(default='default_atap', max_length=50),
        ),
        migrations.AddField(
            model_name='shelter',
            name='kolom_bangunan',
            field=models.CharField(default='default_kolom_bangunan', max_length=50),
        ),
        migrations.AddField(
            model_name='shelter',
            name='rangka_atap',
            field=models.CharField(default='default_rangka_atap', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
