# Generated by Django 4.2.9 on 2024-08-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_kriteria_shelter_atap_shelter_kolom_bangunan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kriteria',
            name='atap',
        ),
        migrations.RemoveField(
            model_name='kriteria',
            name='kolom_bangunan',
        ),
        migrations.RemoveField(
            model_name='kriteria',
            name='rangka_atap',
        ),
        migrations.AddField(
            model_name='kriteria',
            name='bobot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kriteria',
            name='nama_kriteria',
            field=models.CharField(default='Default Kriteria', max_length=50),
        ),
        migrations.AddField(
            model_name='kriteria',
            name='sub_kriteria',
            field=models.CharField(default='Default Sub Kriteria', max_length=50),
        ),
    ]
