# Generated by Django 4.2.9 on 2024-08-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_kriteria_atap_remove_kriteria_kolom_bangunan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='nama_kriteria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='sub_kriteria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
