# Generated by Django 4.2.9 on 2024-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_kriteria_bobot_alter_kriteria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='bobot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='nama_kriteria',
            field=models.CharField(default='Default Kriteria', max_length=50),
        ),
        migrations.AlterField(
            model_name='kriteria',
            name='sub_kriteria',
            field=models.CharField(default='Default Sub Kriteria', max_length=50),
        ),
    ]
