# Generated by Django 4.2.9 on 2024-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_kriteria_bobot_alter_kriteria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='status',
            field=models.CharField(default='default_status', max_length=50),
        ),
    ]
