# Generated by Django 4.2.9 on 2024-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shelter_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atap', models.CharField(max_length=50)),
                ('rangka_atap', models.CharField(max_length=50)),
                ('kolom_bangunan', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
            },
        ),
    ]
