# Generated by Django 4.2.9 on 2024-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_train'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='status',
            new_name='decision',
        ),
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
