# Generated by Django 4.2.9 on 2024-08-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_status_train_decision_alter_train_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AlterField(
            model_name='train',
            name='kolom_bangunan',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
