# Generated by Django 4.2.9 on 2024-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_train_id_alter_train_kolom_bangunan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude_longitude', models.CharField(max_length=255)),
                ('atap', models.CharField(max_length=50)),
                ('rangka_atap', models.CharField(max_length=50)),
                ('kolom_bangunan', models.CharField(max_length=50)),
                ('decision', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.AddField(
            model_name='train',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='kolom_bangunan',
            field=models.CharField(max_length=50),
        ),
    ]
