# Generated by Django 4.2.9 on 2024-08-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_classification_train_id_alter_train_kolom_bangunan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
